const fs = require('fs');
const path = require('path');

const articlesPath = path.join(__dirname, '..', 'data', 'articles.json');
const articles = JSON.parse(fs.readFileSync(articlesPath, 'utf8'));

const newArticles = [
  {
    _id: { $oid: '6a55c3683a493cdd2a768301' },
    slug: 'un-general-assembly-adopts-landmark-treaty-ai-sovereignty-2026',
    title: 'UN General Assembly Adopts Landmark Treaty on Global AI Sovereignty and Digital Border Security',
    deck: 'Diplomats from 174 nations establish binding standards for algorithmic oversight, protecting critical democratic infrastructure, and preventing cross-border automated disinformation campaigns.',
    image: '/assets/upload/news/news-un-general-assembly-ai-sovereignty-treaty-2026.webp',
    tag: 'POLITICS',
    tagColor: 'red',
    author: 'Carlos Mendoza Reyes',
    authorRole: 'Politics Reporter',
    authorAvatar: '/assets/upload/authors/carlos-mendoza-reyes.webp',
    time: '10/09/2026',
    readTime: '5 min',
    comments: 0,
    category: 'politics',
    breadcrumbCategory: 'Politics',
    tagLabel: 'POLITICS',
    headline: 'UN General Assembly Adopts Landmark Treaty on Global AI Sovereignty and Digital Border Security',
    standfirst: 'Diplomats from 174 nations establish binding standards for algorithmic oversight, protecting critical democratic infrastructure, and preventing cross-border automated disinformation campaigns.',
    caption: 'United Nations delegates cast consensus votes on the historic International Digital Sovereignty Accord in New York',
    body: [
      '<p><strong>New York / Geneva:</strong> In an unprecedented diplomatic breakthrough, the United Nations General Assembly has officially ratified the International Digital Sovereignty and Artificial Intelligence Accord, establishing the first universally recognized multilateral framework governing autonomous computation, cyber frontiers, and algorithmic transparency across sovereign states.</p>',
      '<p>The landmark treaty, approved by a commanding majority of 174 member states, culminates nearly three years of intensive intergovernmental negotiations conducted across Geneva, New York, and regional ministerial summits. The agreement introduces legally binding restrictions on the deployment of state-sponsored autonomous cyber weaponry, sets stringent accountability mandates for generative artificial intelligence models operating within public administration, and establishes mutual legal assistance protocols to counteract sophisticated synthetic disinformation operations aimed at sovereign democratic elections.</p>',
      '<h4>Core Pillars of the New Multilateral Framework</h4>',
      '<p>The comprehensive treaty centers on four fundamental pillars engineered to modernize international law for the computational era:</p>',
      '<p>First, it asserts national sovereign jurisdiction over critical computational infrastructure, domestic citizen data repositories, and localized fiber-optic landing hubs, preventing foreign extraterritorial data seizures without transparent judicial review. Second, it mandates verifiable cryptographic watermarking and provenance tracking for synthetic multimedia distributed across commercial broadcasting and social networking platforms.</p>',
      '<p>Third, the accord institutes a high-level International Algorithmic Safety Council, headquartered in Vienna, tasked with conducting standardized safety audits on frontier foundation models before their cross-border commercial deployment. Finally, it allocates dedicated technical assistance and multilateral funding mechanisms to assist developing nations in modernizing sovereign cloud architectures and training domestic regulatory authorities.</p>',
      '<h4>Diplomatic Alignment and Global Reactions</h4>',
      '<p>\"Today, the international community has collectively demonstrated that rapid technological acceleration need not eclipse democratic accountability or national sovereignty,\" declared the UN Secretary-General during the formal signing ceremony in the General Assembly Hall in New York. \"We have established unambiguous red lines against malicious algorithmic interference while preserving the open, interoperable digital architecture that drives global scientific innovation and economic prosperity.\"</p>',
      '<p>The European Union, Latin American diplomatic delegations, and key Asia-Pacific nations strongly endorsed the final accord, highlighting its alignment with existing international human rights conventions and digital marketplace regulations. Negotiators from the United States and emerging economic powers praised the balance between robust cyber resilience mandates and protections for private enterprise research investments.</p>',
      '<h4>Implementation Roadmaps and Sectoral Impact</h4>',
      '<p>Global technology conglomerates, defense analysts, and civil society organizations have begun assessing the operational ramifications of the new regulatory baseline. Beginning in the first quarter of 2027, member states will harmonize domestic telecommunications and data privacy legislation with the treaty’s global interoperability mandates.</p>',
      '<p>International policy observers project that the treaty will stimulate substantial capital expenditure in verifiable cybersecurity architectures, sovereign cryptographic authentication protocols, and localized enterprise cloud infrastructure, creating a more predictable and legally secure environment for transatlantic and transpacific trade.</p>'
    ],
    tags: ['#politics', '#UnitedNations', '#AISovereignty', '#CyberSecurity', '#GlobalGovernance', '#FinancialJournal'],
    related: [],
    status: 'Published',
    views: 0,
    isBreaking: true,
    isFeatured: true,
    publishedDate: '2026-09-10T14:30:00.000Z',
    metaTitle: 'UN General Assembly Adopts Historic Treaty on AI Sovereignty in 2026',
    metaDescription: '174 nations ratify historic UN treaty establishing binding global rules for artificial intelligence governance, cybersecurity, and digital sovereignty.',
    targetKeyword: 'UN AI treaty 2026, digital sovereignty accord, global cybersecurity regulations, United Nations General Assembly, Financial Journal politics',
    canonicalUrl: 'https://www.financial-journal.xyz/politics/un-general-assembly-adopts-landmark-treaty-ai-sovereignty-2026',
    isOpinion: false,
    categorySlug: 'politics'
  },
  {
    _id: { $oid: '6a55c3683a493cdd2a768302' },
    slug: 'semiconductor-giants-unveil-transatlantic-packaging-quantum-corridors-2026',
    title: 'Semiconductor Giants Unveil $120 Billion Transatlantic Advanced Packaging and Quantum Chip Corridors',
    deck: 'Global semiconductor leaders and international trade alliances announce integrated manufacturing hubs to scale 1.4nm logic nodes, sub-nanometer 3D packaging, and fault-tolerant quantum co-processors.',
    image: '/assets/upload/news/news-semiconductor-transatlantic-quantum-packaging-2026.webp',
    tag: 'TECHNOLOGY',
    tagColor: 'gray',
    author: 'Sofía Herrera Luna',
    authorRole: 'Technology Editor',
    authorAvatar: '/assets/upload/authors/sofia-herrera-luna.webp',
    time: '10/09/2026',
    readTime: '5 min',
    comments: 0,
    category: 'technology',
    breadcrumbCategory: 'Technology',
    tagLabel: 'TECHNOLOGY',
    headline: 'Semiconductor Giants Unveil $120 Billion Transatlantic Advanced Packaging and Quantum Chip Corridors',
    standfirst: 'Global semiconductor leaders and international trade alliances announce integrated manufacturing hubs to scale 1.4nm logic nodes, sub-nanometer 3D packaging, and fault-tolerant quantum co-processors.',
    caption: 'State-of-the-art cleanroom clean environments and automated lithography systems in new semiconductor mega-fab facilities',
    body: [
      '<p><strong>Dresden / Austin / Tokyo:</strong> A consortium of the world’s leading semiconductor manufacturers, fabless design houses, and multilateral economic development agencies has unveiled a coordinated $120 billion capital expenditure program aimed at constructing resilient advanced packaging and quantum computing fabrication corridors across North America, Europe, and East Asia.</p>',
      '<p>The strategic industrial partnership addresses surging global demand for high-density computational clusters required by hyperscale artificial intelligence training centers, autonomous vehicular navigation platforms, and sovereign high-performance computing networks. The initiative represents the largest cross-border co-investment in microelectronics manufacturing history.</p>',
      '<h4>Revolutionizing Advanced Heterogeneous Packaging</h4>',
      '<p>At the center of the technological roadmap is the expansion of next-generation 3D wafer-on-wafer stacking and hybrid bonding architectures. As traditional geometric transistor scaling approaches atomic physical limits on 1.4-nanometer nodes, advanced packaging has become the paramount determinant of processing throughput, interconnect latency, and thermal efficiency.</p>',
      '<p>The newly commissioned fabrication facilities in Saxony, Texas, and Kumamoto will utilize extreme ultraviolet (High-NA EUV) lithography combined with direct copper-to-copper interconnects, enabling memory bandwidth to multiply eightfold while reducing operational power consumption by more than 42% compared to contemporary standards.</p>',
      '<h4>Integration of Commercial Quantum Co-Processors</h4>',
      '<p>Beyond silicon-based logic, the industrial corridor allocates $28 billion specifically toward standardizing cryogenic interfaces for fault-tolerant photonic and superconducting quantum co-processors. These modular quantum units are designed to slot directly into existing data center architectures, offloading complex cryptographic permutations, molecular drug synthesis modeling, and grid-scale logistics optimization.</p>',
      '<p>\"We are witnessing the convergence of nanoscale silicon engineering and commercial quantum capability,\" stated the chief technology executive leading the consortium. \"By establishing interoperable packaging standards across three continents, we ensure supply chain redundancy and eliminate single-point vulnerabilities in critical microchip manufacturing.\"</p>',
      '<h4>Geopolitical and Capital Market Implications</h4>',
      '<p>Financial markets rallied sharply following the announcement, with semiconductor equipment vendors, specialty gas suppliers, and optical lithography providers seeing notable index appreciations. Public finance authorities in Germany, Japan, and the United States emphasized that the collaborative corridor model avoids zero-sum subsidy competition, fostering specialized regional supply ecosystems that reinforce global trade stability.</p>'
    ],
    tags: ['#technology', '#Semiconductors', '#QuantumComputing', '#ChipPackaging', '#TechInnovation', '#FinancialJournal'],
    related: [],
    status: 'Published',
    views: 0,
    isBreaking: false,
    isFeatured: true,
    publishedDate: '2026-09-10T13:45:00.000Z',
    metaTitle: 'Semiconductor Giants Unveil $120B Advanced Chip & Quantum Packaging Hubs',
    metaDescription: 'Global semiconductor consortium announces $120 billion investment in 1.4nm advanced packaging and quantum computing manufacturing corridors.',
    targetKeyword: 'semiconductor advanced packaging 2026, quantum chips, EUV lithography, chip manufacturing corridor, Financial Journal technology',
    canonicalUrl: 'https://www.financial-journal.xyz/technology/semiconductor-giants-unveil-transatlantic-packaging-quantum-corridors-2026',
    isOpinion: false,
    categorySlug: 'technology'
  },
  {
    _id: { $oid: '6a55c3683a493cdd2a768303' },
    slug: 'historic-high-seas-conservation-compact-global-ocean-fund-2026',
    title: 'Historic High-Seas Conservation Compact Enters Force with $50 Billion Global Ocean Protection Fund',
    deck: 'International treaty legally safeguards 30% of international waters, introducing automated satellite enforcement, strict seabed mineral moratoria, and blue carbon financing mechanisms.',
    image: '/assets/upload/news/news-global-ocean-treaty-conservation-fund-2026.webp',
    tag: 'ENVIRONMENT',
    tagColor: 'green',
    author: 'Andrés Silva Vargas',
    authorRole: 'Environment Editor',
    authorAvatar: '/assets/upload/authors/andres-silva-vargas.webp',
    time: '10/09/2026',
    readTime: '5 min',
    comments: 0,
    category: 'environment',
    breadcrumbCategory: 'Environment',
    tagLabel: 'ENVIRONMENT',
    headline: 'Historic High-Seas Conservation Compact Enters Force with $50 Billion Global Ocean Protection Fund',
    standfirst: 'International treaty legally safeguards 30% of international waters, introducing automated satellite enforcement, strict seabed mineral moratoria, and blue carbon financing mechanisms.',
    caption: 'Oceanographic research vessels and autonomous environmental monitoring buoys deployed across international waters',
    body: [
      '<p><strong>Bonn / Brest:</strong> In a defining moment for international marine conservation, the United Nations High Seas Biodiversity Treaty has officially entered into legal force following its 60th ratification, establishing comprehensive legal protection across international waters covering nearly two-thirds of the planet’s oceans.</p>',
      '<p>Accompanying the treaty’s activation is the launch of the $50 billion Global Ocean Protection Fund, backed by multilateral development banks, philanthropic endowments, and sovereign green bonds. The capital will finance autonomous satellite surveillance, maritime ranger fleets, and marine ecosystem restoration projects across key migratory biodiversity corridors in the Atlantic, Pacific, and Southern oceans.</p>',
      '<h4>Enforcing the 30x30 Conservation Target</h4>',
      '<p>The compact provides the long-sought enforcement mechanism to fulfill the Global Biodiversity Framework’s mandate to protect 30% of the planet’s marine territories by 2030. Under the treaty’s terms, high-seas commercial exploitation, destructive industrial bottom trawling, and unmonitored waste discharge are strictly prohibited within designated Highly Protected Marine Areas (HPMAs).</p>',
      '<p>Furthermore, the treaty institutes an immediate precautionary moratorium on commercial deep-seabed polymetallic nodule mining until rigorous, independent environmental impact benchmarks can prove zero irreversible ecological degradation to abyssal benthic ecosystems.</p>',
      '<h4>Satellite AI Monitoring and Blue Carbon Markets</h4>',
      '<p>To monitor compliance across vast oceanic expanses, an international surveillance grid combining high-resolution synthetic aperture radar (SAR), automated vessel identification (AIS) tracking, and autonomous solar-powered surface drones will operate under the auspices of the International Maritime Organization (IMO) and partner scientific agencies.</p>',
      '<p>The treaty also unlocks sovereign blue carbon credit mechanisms, allowing coastal and island nations to monetize verifiable ocean carbon sequestration through mangrove restoration, coastal kelp forest preservation, and oceanic biological pump stewardship on regulated global carbon exchanges.</p>',
      '<h4>Global Economic and Ecological Horizon</h4>',
      '<p>\"Our oceans are the primary thermoregulatory engine of our planet and the lifeblood of global weather systems,\" emphasized the Executive Director of the UN Environment Programme. \"By establishing enforceable governance over the global commons, the international community has chosen long-term ecological security over short-term resource depletion.\"</p>',
      '<p>Economists and sustainable finance leaders project that the legal clarity provided by the treaty will mobilize hundreds of billions in sustainable aquaculture investments, marine biotechnology research, and zero-emission green shipping corridors throughout the remainder of the decade.</p>'
    ],
    tags: ['#environment', '#OceanConservation', '#HighSeasTreaty', '#BlueEconomy', '#ClimateAction', '#FinancialJournal'],
    related: [],
    status: 'Published',
    views: 0,
    isBreaking: false,
    isFeatured: true,
    publishedDate: '2026-09-10T13:00:00.000Z',
    metaTitle: 'Historic High Seas Conservation Treaty Enters Force with $50B Ocean Fund',
    metaDescription: 'UN High Seas Biodiversity Treaty enters force protecting 30% of global oceans with a $50 billion conservation fund and seabed mining limits.',
    targetKeyword: 'high seas treaty 2026, global ocean conservation, blue economy, seabed mining moratorium, Financial Journal environment',
    canonicalUrl: 'https://www.financial-journal.xyz/environment/historic-high-seas-conservation-compact-global-ocean-fund-2026',
    isOpinion: false,
    categorySlug: 'environment'
  },
  {
    _id: { $oid: '6a55c3683a493cdd2a768304' },
    slug: 'who-global-health-coalition-ratifies-pathogen-surveillance-accord-2026',
    title: 'WHO and Global Health Coalition Ratify Universal Pathogen Surveillance and Vaccine Access Accord',
    deck: 'World Health Assembly adopts comprehensive pandemic readiness treaty ensuring real-time genomic data sharing, decentralized regional vaccine manufacturing, and equitable biomedical access.',
    image: '/assets/upload/news/news-who-global-pathogen-surveillance-accord-2026.webp',
    tag: 'HEALTH',
    tagColor: 'blue',
    author: 'Valentina Castro Ruiz',
    authorRole: 'Health Editor',
    authorAvatar: '/assets/upload/authors/valentina-castro-ruiz.webp',
    time: '10/09/2026',
    readTime: '5 min',
    comments: 0,
    category: 'health',
    breadcrumbCategory: 'Health',
    tagLabel: 'HEALTH',
    headline: 'WHO and Global Health Coalition Ratify Universal Pathogen Surveillance and Vaccine Access Accord',
    standfirst: 'World Health Assembly adopts comprehensive pandemic readiness treaty ensuring real-time genomic data sharing, decentralized regional vaccine manufacturing, and equitable biomedical access.',
    caption: 'Epidemiologists and laboratory researchers operating automated genomic sequencing workstations in global health facility',
    body: [
      '<p><strong>Geneva / Nairobi / Singapore:</strong> In a historic session of the World Health Assembly, representatives from 194 member nations have officially ratified the Universal Pathogen Intelligence and Medical Countermeasures Accord, cementing a legally binding international regime for early infectious disease detection and equitable pharmaceutical distribution.</p>',
      '<p>The comprehensive treaty rectifies long-standing vulnerabilities in global health architecture exposed by past epidemics. It mandates open-source, real-time sharing of biological pathogen sequencing data while guaranteeing that developing economies receive priority access to localized manufacturing rights, raw precursor chemicals, and finished therapeutic treatments during declared international health emergencies.</p>',
      '<h4>Decentralized mRNA and Biomanufacturing Hubs</h4>',
      '<p>A cornerstone of the ratified agreement is the establishment of twelve interconnected regional biomanufacturing hubs spanning Latin America, Sub-Saharan Africa, South Asia, and the Middle East. Financed through a dedicated $30 billion multilateral health resilience facility, these facilities will maintain continuous commercial production of routine childhood vaccines during standard periods while possessing automated capacity to pivot to rapid-scale epidemic response within 60 days of a novel pathogen alert.</p>',
      '<p>International biotechnology licensors and pharmaceutical developers will contribute intellectual property and standardized modular synthesis protocols into a shared Global Biomedical Innovation Commons managed under World Intellectual Property Organization (WIPO) and WHO oversight.</p>',
      '<h4>Real-Time Global Genomic Surveillance System</h4>',
      '<p>The accord introduces the International Genomic Sentinel Network, deploying standardized digital sequencing equipment across international transportation hubs, regional clinical centers, and wildlife-domestic animal interfaces worldwide.</p>',
      '<p>Advanced machine learning algorithms will continuously analyze anonymized wastewater and clinical samples to flag unusual mutational signatures, enabling epidemiologists to identify and isolate novel viral or antimicrobial-resistant bacterial strains weeks before widespread population transmission occurs.</p>',
      '<h4>Ethical Guarantees and Supply Chain Integrity</h4>',
      '<p>\"Global health security is fundamentally indivisible: no community is protected until every healthcare system possesses the diagnostic and therapeutic tools to respond decisively,\" stated the WHO Director-General in closing remarks. \"This treaty establishes equity and shared technological capability as the bedrock of global biosecurity.\"</p>',
      '<p>Global medical supply chains, personal protective equipment manufacturers, and public health ministries have welcomed the accord, anticipating that standardized international customs waivers for diagnostic materials will eliminate export bans and logistics bottlenecks in future humanitarian emergencies.</p>'
    ],
    tags: ['#health', '#WHO', '#PandemicAccord', '#GenomicSurveillance', '#PublicHealth', '#FinancialJournal'],
    related: [],
    status: 'Published',
    views: 0,
    isBreaking: false,
    isFeatured: true,
    publishedDate: '2026-09-10T12:15:00.000Z',
    metaTitle: 'WHO Ratifies Historic Global Pathogen Surveillance & Vaccine Access Accord',
    metaDescription: '194 nations ratify historic WHO pandemic preparedness treaty guaranteeing real-time genomic data sharing and decentralized vaccine production.',
    targetKeyword: 'WHO pandemic treaty 2026, global pathogen surveillance, vaccine manufacturing hubs, World Health Assembly, Financial Journal health',
    canonicalUrl: 'https://www.financial-journal.xyz/health/who-global-health-coalition-ratifies-pathogen-surveillance-accord-2026',
    isOpinion: false,
    categorySlug: 'health'
  },
  {
    _id: { $oid: '6a55c3683a493cdd2a768305' },
    slug: 'international-sports-federations-sustainable-multi-city-protocol-2026',
    title: 'International Sports Federations Institute $35 Billion Sustainable Multi-City Infrastructure Protocol',
    deck: 'Global sporting bodies mandate regional stadium-sharing models, zero-carbon high-speed rail connections, and permanent community legacy requirements for major international championships.',
    image: '/assets/upload/news/news-sustainable-multi-city-stadium-protocol-2026.webp',
    tag: 'SPORTS',
    tagColor: 'green',
    author: 'Javier Ortiz Navarro',
    authorRole: 'Sports Correspondent',
    authorAvatar: '/assets/upload/authors/javier-ortiz-navarro.webp',
    time: '10/09/2026',
    readTime: '5 min',
    comments: 0,
    category: 'sports',
    breadcrumbCategory: 'Sports',
    tagLabel: 'SPORTS',
    headline: 'International Sports Federations Institute $35 Billion Sustainable Multi-City Infrastructure Protocol',
    standfirst: 'Global sporting bodies mandate regional stadium-sharing models, zero-carbon high-speed rail connections, and permanent community legacy requirements for major international championships.',
    caption: 'Modern solar-powered multi-purpose arena integrated with electrified metropolitan transit network',
    body: [
      '<p><strong>Zurich / Lausanne / London:</strong> In a transformative shift for international athletics and tournament economics, a joint assembly of major global sporting governing bodies—including the International Olympic Committee (IOC), FIFA, and regional continental confederations—has enacted the Sustainable Multi-City Infrastructure Protocol, fundamentally restructuring how mega-events are bid for, financed, and executed.</p>',
      '<p>The new regulatory framework bans the construction of single-use \"white elephant\" mega-stadiums, requiring future host bidding alliances to utilize existing sports infrastructure distributed across interconnected metropolitan clusters linked by zero-emission electrified rail systems.</p>',
      '<h4>Ending Single-City Tournament Financial Burdens</h4>',
      '<p>The accord responds to decades of mounting municipal debt and infrastructure underutilization following major international tournaments. Under the new guidelines, bids are evaluated primarily on their long-term urban integration, circular economy construction certifications, and community accessibility rather than headline capital expenditure figures.</p>',
      '<p>Host nations are now required to demonstrate that at least 85% of competition venues are either pre-existing or modular demountable structures engineered for relocation to underserved grassroots athletic communities following the conclusion of championship tournaments.</p>',
      '<h4>Green Energy and Public Transit Integration</h4>',
      '<p>The protocol introduces strict environmental benchmarks backed by a $35 billion Sustainable Venue Green Bond standard. All participating tournament arenas must operate on 100% certified renewable energy, implement closed-loop greywater recycling systems, and enforce zero single-use plastic waste mandates across spectator concourses.</p>',
      '<p>Furthermore, host organizing committees must guarantee that all competition sites are connected via rapid electrified mass transit lines capable of moving spectator volumes without relying on expanded highway infrastructure or domestic aviation corridors.</p>',
      '<h4>Private Equity and Long-Term Sports Asset Valuation</h4>',
      '<p>\"The era of wasteful, single-use monument building in global sports has permanently concluded,\" stated the President of the Joint Sports Sustainability Council. \"Modern sporting celebrations must leave durable, debt-free social and economic dividends for host communities while showcasing the highest levels of competitive excellence.\"</p>',
      '<p>Institutional infrastructure investors, municipal bond underwriters, and urban planners have praised the transition. Sports business analysts calculate that multi-city regional hosting models reduce municipal hosting capital expenditures by up to 60% while expanding long-term corporate sponsorship and commercial broadcasting returns across broader regional consumer demographics.</p>'
    ],
    tags: ['#sports', '#SportsBusiness', '#SustainableStadiums', '#OlympicLegacy', '#FIFA', '#FinancialJournal'],
    related: [],
    status: 'Published',
    views: 0,
    isBreaking: false,
    isFeatured: true,
    publishedDate: '2026-09-10T11:30:00.000Z',
    metaTitle: 'Global Sports Federations Institute $35B Sustainable Multi-City Stadium Protocol',
    metaDescription: 'IOC, FIFA, and global sports federations mandate multi-city venue sharing and zero-carbon transit for major international tournaments.',
    targetKeyword: 'sports infrastructure protocol 2026, sustainable stadiums, multi-city tournament hosting, FIFA IOC sustainability, Financial Journal sports',
    canonicalUrl: 'https://www.financial-journal.xyz/sports/international-sports-federations-sustainable-multi-city-protocol-2026',
    isOpinion: false,
    categorySlug: 'sports'
  }
];

// Verify character counts
console.log('=== VERIFYING CHARACTER COUNTS (> 2000 chars) ===');
newArticles.forEach((art, i) => {
  const fullText = art.body.join(' ');
  console.log(`${i + 1}. [${art.category.toUpperCase()}] ${art.title}`);
  console.log(`   Characters: ${fullText.length} | Meets 2000+ constraint: ${fullText.length >= 2000 ? 'YES' : 'NO'}`);
});

// Prepend to articles list
const updatedArticles = [...newArticles, ...articles];
fs.writeFileSync(articlesPath, JSON.stringify(updatedArticles, null, 2), 'utf8');
console.log(`\nSuccessfully saved! Total articles in data/articles.json: ${updatedArticles.length}`);
